title: Matt Chapman # your name (or website title) here
logo: "/images/playing_drums.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  xyz
  <br><br>
  abc
  <br><br>
  <a href="https://www.linkedin.com/in/matt-chapman-ba8488118/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 - your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
